export interface MockEstablishment {
  id: string;
  nameTh: string;
  address: string;
  province: string;
  category: string;
  businessType: string;
  latitude: number;
  longitude: number;
}

export const MOCK_ESTABLISHMENTS: MockEstablishment[] = [
  // --- โรงแรม (hotel) ---
  {
    id: "mock-est-hotel-bkk",
    nameTh: "โรงแรม แกรนด์ บางกอก รีสอร์ท",
    address: "99 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพมหานคร 10110",
    province: "กรุงเทพมหานคร",
    category: "hotel",
    businessType: "โรงแรม",
    latitude: 13.7367,
    longitude: 100.5231,
  },
  {
    id: "mock-est-hotel-cmi",
    nameTh: "โรงแรม เชียงใหม่ ลานนา เฮอริเทจ",
    address: "12 ถนนท่าแพ ตำบลช้างคลาน อำเภอเมืองเชียงใหม่ เชียงใหม่ 50100",
    province: "เชียงใหม่",
    category: "hotel",
    businessType: "โรงแรม",
    latitude: 18.7883,
    longitude: 98.9853,
  },
  {
    id: "mock-est-hotel-cby",
    nameTh: "เดอะ บลู ฮาร์เบอร์ โฮเทล พัทยา",
    address: "202 หมู่ 5 ถนนเลียบชายหาด ตำบลนาเกลือ อำเภอบางละมุง ชลบุรี 20150",
    province: "ชลบุรี",
    category: "hotel",
    businessType: "โรงแรม",
    latitude: 12.9235,
    longitude: 100.8824,
  },
  {
    id: "mock-est-hotel-nma",
    nameTh: "เขาใหญ่ กรีนวัลเล่ย์ รีสอร์ท",
    address: "45 หมู่ 8 ถนนธนะรัชต์ ตำบลหมูสี อำเภอปากช่อง นครราชสีมา 30130",
    province: "นครราชสีมา",
    category: "hotel",
    businessType: "โรงแรม",
    latitude: 14.5684,
    longitude: 101.4132,
  },
  {
    id: "mock-est-hotel-hkt",
    nameTh: "ภูเก็ต แซนด์ รีสอร์ท แอนด์ สปา",
    address: "88 ถนนทวีวงศ์ ตำบลป่าตอง อำเภอกะทู้ ภูเก็ต 83150",
    province: "ภูเก็ต",
    category: "hotel",
    businessType: "โรงแรม",
    latitude: 7.8972,
    longitude: 98.2956,
  },

  // --- โรงพยาบาล (hospital) ---
  {
    id: "mock-est-hosp-bkk",
    nameTh: "โรงพยาบาลกรุงเทพ เมดิคอล เซ็นเตอร์",
    address: "2 ถนนเพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพมหานคร 10310",
    province: "กรุงเทพมหานคร",
    category: "hospital",
    businessType: "โรงพยาบาล",
    latitude: 13.7486,
    longitude: 100.5824,
  },
  {
    id: "mock-est-hosp-cmi",
    nameTh: "โรงพยาบาลลานนา เชียงใหม่",
    address: "1 ถนนซุปเปอร์ไฮเวย์ ตำบลป่าตัน อำเภอเมืองเชียงใหม่ เชียงใหม่ 50300",
    province: "เชียงใหม่",
    category: "hospital",
    businessType: "โรงพยาบาล",
    latitude: 18.8142,
    longitude: 98.9954,
  },
  {
    id: "mock-est-hosp-cby",
    nameTh: "โรงพยาบาลกรุงเทพพัทยา",
    address: "301 หมู่ 6 ถนนสุขุมวิท ตำบลนาเกลือ อำเภอบางละมุง ชลบุรี 20150",
    province: "ชลบุรี",
    category: "hospital",
    businessType: "โรงพยาบาล",
    latitude: 12.9431,
    longitude: 100.9023,
  },
  {
    id: "mock-est-hosp-nma",
    nameTh: "โรงพยาบาลมหาราชนครราชสีมา",
    address: "49 ถนนช้างเผือก ตำบลในเมือง อำเภอเมืองนครราชสีมา นครราชสีมา 30000",
    province: "นครราชสีมา",
    category: "hospital",
    businessType: "โรงพยาบาล",
    latitude: 14.9812,
    longitude: 102.1034,
  },
  {
    id: "mock-est-hosp-hkt",
    nameTh: "โรงพยาบาลกรุงเทพภูเก็ต",
    address: "2/1 ถนนหงษ์หยกอุทิศ ตำบลตลาดใหญ่ อำเภอเมืองภูเก็ต ภูเก็ต 83000",
    province: "ภูเก็ต",
    category: "hospital",
    businessType: "โรงพยาบาล",
    latitude: 7.8987,
    longitude: 98.3821,
  },

  // --- โรงงาน (factory) ---
  {
    id: "mock-est-fact-bkk",
    nameTh: "บริษัท กรุงเทพการทอและการย้อม จำกัด",
    address: "105 หมู่ 3 ถนนสุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพมหานคร 10140",
    province: "กรุงเทพมหานคร",
    category: "factory",
    businessType: "โรงงาน (ร.ง.4)",
    latitude: 13.6789,
    longitude: 100.5123,
  },
  {
    id: "mock-est-fact-cmi",
    nameTh: "โรงงานเซรามิคศิลาดล เชียงใหม่",
    address: "122 หมู่ 2 ถนนเชียงใหม่-ดอยสะเก็ด ตำบลป่าป้อง อำเภอดอยสะเก็ด เชียงใหม่ 50220",
    province: "เชียงใหม่",
    category: "factory",
    businessType: "โรงงาน (ร.ง.4)",
    latitude: 18.8654,
    longitude: 99.1245,
  },
  {
    id: "mock-est-fact-cby",
    nameTh: "โรงงานผลิตชิ้นส่วนยานยนต์ อมตะซิตี้",
    address: "700/45 หมู่ 1 นิคมอุตสาหกรรมอมตะซิตี้ ตำบลคลองตำหรุ อำเภอเมืองชลบุรี ชลบุรี 20000",
    province: "ชลบุรี",
    category: "factory",
    businessType: "โรงงาน (ร.ง.4)",
    latitude: 13.4123,
    longitude: 101.0124,
  },
  {
    id: "mock-est-fact-nma",
    nameTh: "โรงงานแปรรูปพืชไร่นครราชสีมา",
    address: "88 หมู่ 5 ถนนมิตรภาพ ตำบลโคกกรวด อำเภอเมืองนครราชสีมา นครราชสีมา 30280",
    province: "นครราชสีมา",
    category: "factory",
    businessType: "โรงงาน (ร.ง.4)",
    latitude: 14.9214,
    longitude: 101.9845,
  },
  {
    id: "mock-est-fact-hkt",
    nameTh: "โรงงานสับปะรดแปรรูป ภูเก็ต โปรดักส์",
    address: "54 หมู่ 4 ถนนเทพกระษัตรี ตำบลศรีสุนทร อำเภอถลาง ภูเก็ต 83110",
    province: "ภูเก็ต",
    category: "factory",
    businessType: "โรงงาน (ร.ง.4)",
    latitude: 7.9823,
    longitude: 98.3845,
  },

  // --- สถานศึกษา (education) ---
  {
    id: "mock-est-educ-bkk",
    nameTh: "โรงเรียนกรุงเทพคริสเตียนวิทยาลัย",
    address: "35 ถนนประมวญ แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500",
    province: "กรุงเทพมหานคร",
    category: "education",
    businessType: "สถานศึกษา",
    latitude: 13.7214,
    longitude: 100.5234,
  },
  {
    id: "mock-est-educ-cmi",
    nameTh: "มหาวิทยาลัยเชียงใหม่ แคมปัสหลัก",
    address: "239 ถนนห้วยแก้ว ตำบลสุเทพ อำเภอเมืองเชียงใหม่ เชียงใหม่ 50200",
    province: "เชียงใหม่",
    category: "education",
    businessType: "สถานศึกษา",
    latitude: 18.8023,
    longitude: 98.9501,
  },
  {
    id: "mock-est-educ-cby",
    nameTh: "โรงเรียนดาราสมุทร ศรีราชา",
    address: "12 ถนนสุขุมวิท ตำบลศรีราชา อำเภอศรีราชา ชลบุรี 20110",
    province: "ชลบุรี",
    category: "education",
    businessType: "สถานศึกษา",
    latitude: 13.1784,
    longitude: 100.9312,
  },
  {
    id: "mock-est-educ-nma",
    nameTh: "โรงเรียนราชสีมาวิทยาลัย",
    address: "1042 ถนนมิตรภาพ ตำบลในเมือง อำเภอเมืองนครราชสีมา นครราชสีมา 30000",
    province: "นครราชสีมา",
    category: "education",
    businessType: "สถานศึกษา",
    latitude: 14.9734,
    longitude: 102.0567,
  },
  {
    id: "mock-est-educ-hkt",
    nameTh: "โรงเรียนขจรเกียรติศึกษา ภูเก็ต",
    address: "12/9 หมู่ 1 ถนนวิชิตสงคราม ตำบลกะทู้ อำเภอกะทู้ ภูเก็ต 83120",
    province: "ภูเก็ต",
    category: "education",
    businessType: "สถานศึกษา",
    latitude: 7.9012,
    longitude: 98.3423,
  },
];
