import {
  GeometryType,
  PinCategory,
  PinStatus,
  PinType,
  type ApiPin,
} from "@/types/api";
import type { ApiFloor } from "./floor.service";
import type { ApiParcel } from "./parcel.service";
import type { ApiZone } from "./zone.service";

const now = "2026-04-27T00:00:00.000Z";

export const mockPins: ApiPin[] = [
  {
    id: "pin-water-tank-1",
    dataId: "W-001",
    title: "ถังพักน้ำชุมชนกลาง",
    description: "ระดับน้ำและคุณภาพน้ำอยู่ในเกณฑ์ปกติ",
    category: PinCategory.DEVICE,
    type: PinType.WATER,
    tags: ["water", "iot"],
    status: PinStatus.NORMAL,
    isPublic: true,
    geometry: {
      type: GeometryType.POINT,
      coordinates: [99.8272, 13.5486],
      lat: 13.5486,
      lng: 99.8272,
    },
    attributes: {
      value: "86%",
      unit: "ระดับน้ำ",
      location: "โซนกลางเมือง",
    },
    images: [],
    zoneId: "zone-central",
    parcelId: "parcel-market",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-camera-gate",
    dataId: "CCTV-014",
    title: "กล้องทางเข้าศูนย์บริการ",
    description: "กล้องวงจรปิดหน้าทางเข้าหลัก",
    category: PinCategory.DEVICE,
    type: PinType.CAMERA,
    tags: ["security"],
    status: PinStatus.NORMAL,
    isPublic: true,
    geometry: {
      type: GeometryType.POINT,
      coordinates: [99.8291, 13.5479],
      lat: 13.5479,
      lng: 99.8291,
    },
    attributes: {
      cameraName: "CCTV Gate 01",
      streamStatus: "online",
    },
    images: [],
    zoneId: "zone-central",
    parcelId: "parcel-service",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-market-license",
    dataId: "LIC-203",
    title: "จุดตรวจใบอนุญาตตลาด",
    description: "พื้นที่ตรวจสถานประกอบการและใบอนุญาต",
    category: PinCategory.MANAGEMENT,
    type: PinType.INFO,
    subtype: "market",
    subtypeNameTh: "ตลาด",
    tags: ["license"],
    status: PinStatus.WARNING,
    isPublic: true,
    geometry: {
      type: GeometryType.POINT,
      coordinates: [99.8256, 13.5474],
      lat: 13.5474,
      lng: 99.8256,
    },
    attributes: {
      owner: "เทศบาลเมืองตัวอย่าง",
      expireDate: "31 ธ.ค. 2567",
    },
    images: [],
    zoneId: "zone-central",
    parcelId: "parcel-market",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-solar-roof",
    dataId: "SOL-002",
    title: "แผงโซลาร์อาคารเทศบาล",
    description: "กำลังผลิตวันนี้ 42 kWh",
    category: PinCategory.SOLAR,
    type: PinType.SOLAR,
    tags: ["energy"],
    status: PinStatus.NORMAL,
    isPublic: true,
    geometry: {
      type: GeometryType.POINT,
      coordinates: [99.8322, 13.5508],
      lat: 13.5508,
      lng: 99.8322,
    },
    attributes: {
      value: "42",
      unit: "kWh",
    },
    images: [],
    zoneId: "zone-north",
    parcelId: "parcel-office",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pin-risk-drainage",
    dataId: "RISK-009",
    title: "จุดเสี่ยงน้ำท่วม",
    description: "ท่อระบายน้ำรอปรับปรุง",
    category: PinCategory.RISK,
    type: PinType.INFO,
    subtype: "warning",
    subtypeNameTh: "จุดเสี่ยง",
    tags: ["risk", "drainage"],
    status: PinStatus.WARNING,
    isPublic: true,
    geometry: {
      type: GeometryType.POINT,
      coordinates: [99.8237, 13.5502],
      lat: 13.5502,
      lng: 99.8237,
    },
    attributes: {
      riskLevel: "ปานกลาง",
    },
    images: [],
    zoneId: "zone-north",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockZones: ApiZone[] = [
  {
    id: "zone-central",
    name: "โซนศูนย์กลางเมือง",
    description: "พื้นที่บริการหลักและตลาดชุมชน",
    type: "WATER_ZONE" as ApiZone["type"],
    color: "#2563EB",
    isActive: true,
    geometry: {
      id: "geom-zone-central",
      type: "POLYGON",
      coordinates: [
        [
          [99.8215, 13.5445],
          [99.8328, 13.5445],
          [99.8342, 13.5515],
          [99.824, 13.5525],
          [99.8215, 13.5445],
        ],
      ],
    },
    _count: { pins: 3 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "zone-north",
    name: "โซนชุมชนเหนือ",
    description: "พื้นที่สำนักงานและชุมชนด้านเหนือ",
    type: "CAMERA_ZONE" as ApiZone["type"],
    color: "#16A34A",
    isActive: true,
    geometry: {
      id: "geom-zone-north",
      type: "POLYGON",
      coordinates: [
        [
          [99.822, 13.5502],
          [99.8358, 13.5501],
          [99.836, 13.557],
          [99.8235, 13.5574],
          [99.822, 13.5502],
        ],
      ],
    },
    _count: { pins: 2 },
    createdAt: now,
    updatedAt: now,
  },
];

export const mockParcels: ApiParcel[] = [
  {
    id: "parcel-market",
    name: "ตลาดชุมชน",
    address: "ถนนเทศบาล 1",
    description: "พื้นที่ตลาดและกิจการค้าปลีก",
    type: "COMMERCIAL" as ApiParcel["type"],
    status: "ACTIVE" as ApiParcel["status"],
    ownerName: "สำนักงานตลาดเทศบาล",
    ownerPhone: "02-000-0001",
    areaSize: 7600,
    landTitle: "10234",
    strokeStyle: "dashed",
    strokeColor: "#F97316",
    fillColor: "#F97316",
    fillOpacity: 0.12,
    zoneId: "zone-central",
    geometry: {
      id: "geom-parcel-market",
      type: "POLYGON",
      coordinates: [
        [
          [99.8234, 13.5458],
          [99.8278, 13.5459],
          [99.8276, 13.5491],
          [99.823, 13.549],
          [99.8234, 13.5458],
        ],
      ],
    },
    _count: { floors: 1, pins: 2 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "parcel-service",
    name: "ศูนย์บริการประชาชน",
    address: "ถนนเทศบาล 2",
    type: "GOVERNMENT" as ApiParcel["type"],
    status: "ACTIVE" as ApiParcel["status"],
    ownerName: "เทศบาลเมืองตัวอย่าง",
    areaSize: 5200,
    strokeStyle: "solid",
    strokeColor: "#2563EB",
    fillColor: "#2563EB",
    fillOpacity: 0.1,
    zoneId: "zone-central",
    geometry: {
      id: "geom-parcel-service",
      type: "POLYGON",
      coordinates: [
        [
          [99.8285, 13.5462],
          [99.832, 13.5463],
          [99.8316, 13.5499],
          [99.8282, 13.5494],
          [99.8285, 13.5462],
        ],
      ],
    },
    _count: { floors: 2, pins: 1 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "parcel-office",
    name: "อาคารสำนักงานเทศบาล",
    address: "ถนนประชาร่วมใจ",
    type: "GOVERNMENT" as ApiParcel["type"],
    status: "ACTIVE" as ApiParcel["status"],
    ownerName: "เทศบาลเมืองตัวอย่าง",
    areaSize: 6400,
    strokeStyle: "solid",
    strokeColor: "#16A34A",
    fillColor: "#16A34A",
    fillOpacity: 0.1,
    zoneId: "zone-north",
    geometry: {
      id: "geom-parcel-office",
      type: "POLYGON",
      coordinates: [
        [
          [99.8298, 13.551],
          [99.8344, 13.5512],
          [99.834, 13.5552],
          [99.8293, 13.555],
          [99.8298, 13.551],
        ],
      ],
    },
    _count: { floors: 3, pins: 1 },
    createdAt: now,
    updatedAt: now,
  },
];

export const mockFloors: ApiFloor[] = [
  {
    id: "floor-market-1",
    level: 1,
    name: "ชั้น 1",
    type: "GROUND" as ApiFloor["type"],
    areaSize: 7600,
    parcelId: "parcel-market",
    _count: { pins: 2 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "floor-service-1",
    level: 1,
    name: "ชั้น 1",
    type: "GROUND" as ApiFloor["type"],
    areaSize: 2600,
    parcelId: "parcel-service",
    _count: { pins: 1 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "floor-office-roof",
    level: 4,
    name: "ดาดฟ้า",
    type: "ROOFTOP" as ApiFloor["type"],
    areaSize: 1200,
    parcelId: "parcel-office",
    _count: { pins: 1 },
    createdAt: now,
    updatedAt: now,
  },
];

export const mockPinCategories = [
  {
    category: PinCategory.INFRASTRUCTURE,
    icon: "building",
    color: "#8B4513",
    nameTh: "โครงสร้างพื้นฐาน",
    subtypes: [
      {
        code: "municipal_office",
        name: "Municipal Office",
        nameTh: "สำนักงานเทศบาล",
        icon: "building",
        color: "#8B4513",
      },
      {
        code: "school",
        name: "School",
        nameTh: "โรงเรียนสังกัด",
        icon: "school",
        color: "#8B4513",
      },
    ],
  },
  {
    category: PinCategory.MANAGEMENT,
    icon: "file-text",
    color: "#9333EA",
    nameTh: "ข้อมูลบริหาร",
    subtypes: [
      {
        code: "market",
        name: "Market",
        nameTh: "ตลาด",
        icon: "market",
        color: "#9333EA",
      },
    ],
  },
  {
    category: PinCategory.RISK,
    icon: "warning",
    color: "#DC2626",
    nameTh: "ความเสี่ยง",
    subtypes: [
      {
        code: "warning",
        name: "Warning Point",
        nameTh: "จุดเสี่ยง",
        icon: "warning",
        color: "#DC2626",
      },
    ],
  },
];

export function cloneMock<T>(value: T): T {
  return structuredClone(value);
}
