// Single source of truth for reading the officer verification token out of a
// scanned QR payload. The QR generated by /officer-card encodes the frontend
// verify page URL (/verify-officer?token=<token>), so the token lives in the
// query string — not in the path. Older/manually produced codes may carry a
// /verify/<token> path or the bare token, so both are still accepted.
//
// Returns null when nothing usable can be read; callers must show an error
// instead of navigating with a junk token.

export function extractOfficerToken(scannedText: string): string | null {
  const value = scannedText.trim();
  if (!value) return null;

  if (/^https?:\/\//i.test(value)) {
    try {
      const url = new URL(value);

      const fromQuery = url.searchParams.get("token")?.trim();
      if (fromQuery) return fromQuery;

      const parts = url.pathname.split("/").filter(Boolean);
      const idx = parts.findIndex((p) => p === "verify" || p === "verify-officer");
      if (idx !== -1 && parts[idx + 1]) {
        return parts.slice(idx + 1).join("/");
      }
    } catch (e) {
      console.error("Failed to parse officer QR URL:", e);
    }
    // A URL we could not read a token out of is not a token itself.
    return null;
  }

  // Not a URL — treat the raw payload as the token when it looks like one.
  return value.includes(" ") ? null : value;
}

/** Path for the verify page, with the token safely encoded. */
export function officerVerifyPath(token: string): string {
  return `/verify-officer?token=${encodeURIComponent(token)}`;
}
